version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  redis:
    image: redis:latest

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
        RAILS_ENV: production
        RAILS_MASTER_KEY: "bc53bd5c46a4cbdaec905af4a1c31795" 



  web:
    build: .
    command: bundle exec rails server -b '0.0.0.0' -p 3000
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: "bc53bd5c46a4cbdaec905af4a1c31795"
      SECRET_KEY_BASE: "bc53bd5c46a4cbdaec905af4a1c31795" 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  db_data:
